const SUPABASE_URL='https://brwtgglxitfotchhnzic.supabase.co';
const SUPABASE_KEY='sb_publishable_f2WHMFXTmzu_2geNI18wTQ_eEBLTvCu';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id), money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2});
async function login(){let {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('loginMsg').textContent=error?error.message:'Logged in';if(!error)start()}
async function logout(){await sb.auth.signOut();location.reload()}
async function start(){let {data:{session}}=await sb.auth.getSession();if(!session)return;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');tab('dashboard')}
async function tab(name){
const c=$('content');
if(name==='dashboard'){let [{count:clients},{count:bills},{data:r},{data:e}]=await Promise.all([sb.from('clients').select('*',{count:'exact',head:true}),sb.from('bills').select('*',{count:'exact',head:true}),sb.from('receipts').select('amount'),sb.from('expenses').select('amount')]);c.innerHTML=`<h2>Dashboard</h2><div class="grid"><div class="stat"><b>${clients||0}</b>Clients</div><div class="stat"><b>${bills||0}</b>Bills</div><div class="stat"><b>${money((r||[]).reduce((s,x)=>s+Number(x.amount),0))}</b>Receipts</div><div class="stat"><b>${money((e||[]).reduce((s,x)=>s+Number(x.amount),0))}</b>Expenses</div></div>`;return}
if(name==='clients'){c.innerHTML=`<h2>Clients</h2><form class="form" onsubmit="addClient(event)"><input id="cn" placeholder="Client name" required><input id="cm" placeholder="Mobile"><input id="ca" placeholder="Address"><input id="cx" placeholder="Matter / Case"><button>Add Client</button></form><div id="list"></div>`;await listClients();return}
if(name==='bills'){c.innerHTML=`<h2>Bills</h2><form class="form" onsubmit="addBill(event)"><input id="bn" placeholder="Bill No." required><input id="bd" type="date" required><input id="bc" placeholder="Client ID" required><input id="bm" placeholder="Matter"><input id="bx" placeholder="Service / Description" required><input id="ba" type="number" step=".01" placeholder="Amount" required><button>Create Bill</button></form><div id="list"></div>`;await listBills();return}
if(name==='receipts'){c.innerHTML=`<h2>Receipts</h2><form class="form" onsubmit="addReceipt(event)"><input id="rn" placeholder="Receipt No." required><input id="rd" type="date" required><input id="rc" placeholder="Client ID" required><input id="rb" placeholder="Bill ID (optional)"><input id="ra" type="number" step=".01" placeholder="Amount" required><select id="rm"><option value="cash">Cash</option><option value="bank">Bank</option><option value="upi">UPI</option><option value="cheque">Cheque</option><option value="other">Other</option></select><button>Add Receipt</button></form><div id="list"></div>`;await listReceipts();return}
if(name==='expenses'){c.innerHTML=`<h2>Expenses</h2><p class="msg">Court Fee અને Internet expense included નથી.</p><form class="form" onsubmit="addExpense(event)"><input id="en" placeholder="Expense No." required><input id="ed" type="date" required><select id="ec"><option value="government">Government</option><option value="professional">Professional</option><option value="office_other">Office / Other</option></select><input id="ei" placeholder="Client ID (optional)"><input id="ex" placeholder="Description" required><input id="ea" type="number" step=".01" placeholder="Amount" required><button>Add Expense</button></form><div id="list"></div>`;await listExpenses();return}
if(name==='ledger'){c.innerHTML=`<h2>Client Ledger</h2><p>Client UUID નાખો:</p><input id="lid" placeholder="Client ID"><button onclick="ledger()">Show Ledger</button><div id="list"></div>`;return}
if(name==='reports'){let {data:b}=await sb.from('bills').select('total,status'),{data:r}=await sb.from('receipts').select('amount'),{data:e}=await sb.from('expenses').select('category,amount');let bt=(b||[]).reduce((s,x)=>s+Number(x.total),0),rt=(r||[]).reduce((s,x)=>s+Number(x.amount),0),gt=(e||[]).filter(x=>x.category==='government').reduce((s,x)=>s+Number(x.amount),0),pt=(e||[]).filter(x=>x.category==='professional').reduce((s,x)=>s+Number(x.amount),0);c.innerHTML=`<h2>Reports</h2><p>Total Bills: <b>${money(bt)}</b></p><p>Total Receipts: <b>${money(rt)}</b></p><p>Outstanding: <b>${money(bt-rt)}</b></p><p>Government Expenses: <b>${money(gt)}</b></p><p>Professional Expenses: <b>${money(pt)}</b></p>`}}
async function addClient(e){e.preventDefault();let {error}=await sb.from('clients').insert({name:cn.value,mobile:cm.value,address:ca.value,matter_ref:cx.value});alert(error?error.message:'Client added');if(!error)listClients()}
async function listClients(){let {data,error}=await sb.from('clients').select('*').order('created_at',{ascending:false});$('list').innerHTML=error?error.message:`<table><tr><th>Name</th><th>Mobile</th><th>Matter</th><th>ID</th></tr>${(data||[]).map(x=>`<tr><td>${x.name}</td><td>${x.mobile||''}</td><td>${x.matter_ref||''}</td><td>${x.id}</td></tr>`).join('')}</table>`}
async function addBill(e){e.preventDefault();let {error}=await sb.from('bills').insert({bill_no:bn.value,bill_date:bd.value,client_id:bc.value,matter_ref:bm.value,description:bx.value,amount:+ba.value});alert(error?error.message:'Bill created');if(!error)listBills()}
async function listBills(){let {data,error}=await sb.from('bills').select('id,bill_no,bill_date,client_id,description,total,status').order('bill_date',{ascending:false});$('list').innerHTML=error?error.message:`<table><tr><th>No.</th><th>Date</th><th>Client ID</th><th>Description</th><th>Total</th><th>Status</th></tr>${(data||[]).map(x=>`<tr><td>${x.bill_no}</td><td>${x.bill_date}</td><td>${x.client_id}</td><td>${x.description}</td><td>${money(x.total)}</td><td>${x.status}</td></tr>`).join('')}</table>`}
async function addReceipt(e){e.preventDefault();let {error}=await sb.from('receipts').insert({receipt_no:rn.value,receipt_date:rd.value,client_id:rc.value,bill_id:rb.value||null,amount:+ra.value,payment_mode:rm.value});alert(error?error.message:'Receipt added');if(!error)listReceipts()}
async function listReceipts(){let {data,error}=await sb.from('receipts').select('*').order('receipt_date',{ascending:false});$('list').innerHTML=error?error.message:`<table><tr><th>No.</th><th>Date</th><th>Client</th><th>Mode</th><th>Amount</th></tr>${(data||[]).map(x=>`<tr><td>${x.receipt_no}</td><td>${x.receipt_date}</td><td>${x.client_id}</td><td>${x.payment_mode}</td><td>${money(x.amount)}</td></tr>`).join('')}</table>`}
async function addExpense(e){e.preventDefault();let {error}=await sb.from('expenses').insert({expense_no:en.value,expense_date:ed.value,category:ec.value,client_id:ei.value||null,description:ex.value,amount:+ea.value});alert(error?error.message:'Expense added');if(!error)listExpenses()}
async function listExpenses(){let {data,error}=await sb.from('expenses').select('*').order('expense_date',{ascending:false});$('list').innerHTML=error?error.message:`<table><tr><th>No.</th><th>Date</th><th>Category</th><th>Description</th><th>Amount</th></tr>${(data||[]).map(x=>`<tr><td>${x.expense_no}</td><td>${x.expense_date}</td><td>${x.category}</td><td>${x.description}</td><td>${money(x.amount)}</td></tr>`).join('')}</table>`}
async function ledger(){let id=$('lid').value,{data:b}=await sb.from('bills').select('bill_date,description,total').eq('client_id',id),{data:r}=await sb.from('receipts').select('receipt_date,payment_mode,amount').eq('client_id',id);let bt=(b||[]).reduce((s,x)=>s+Number(x.total),0),rt=(r||[]).reduce((s,x)=>s+Number(x.amount),0);$('list').innerHTML=`<p>Billed: <b>${money(bt)}</b> · Received: <b>${money(rt)}</b> · Outstanding: <b>${money(bt-rt)}</b></p>`}
sb.auth.onAuthStateChange((_e,session)=>{if(session)start()});start();